services:
  - type: web
    name: smarthaul
    env: python
    plan: free
    buildCommand: pip install -r requirements-free.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
