# Generated by Django 4.2.14 on 2026-07-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='provider',
            new_name='providers_p_service_2e7f16_idx',
            old_name='providers_s_area_7d0f2f_idx',
        ),
        migrations.RenameIndex(
            model_name='provider',
            new_name='providers_p_is_avai_0b7c63_idx',
            old_name='providers_i_avail_3d9f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='provider',
            new_name='providers_p_created_6d07c6_idx',
            old_name='providers_c_created_b6a213_idx',
        ),
        migrations.AddField(
            model_name='provider',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='verification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='verification_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_more_info', 'Needs More Info')], default='pending_review', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['verification_status'], name='providers_p_verific_fcd82d_idx'),
        ),
    ]
