# Generated by Django 4.2.14 on 2026-07-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_calllog_and_dispute_tracking'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_provider_ping_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_custome_0cbf77_idx',
            old_name='bookings_c_status_5f4d1c_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_provide_c56754_idx',
            old_name='bookings_p_status_f4c38a_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_status_233e96_idx',
            old_name='bookings_status_1c8f7e_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_created_1720a2_idx',
            old_name='bookings_created_2d57b1_idx',
        ),
        migrations.RenameIndex(
            model_name='bookingtracking',
            new_name='bookings_bo_booking_26fad2_idx',
            old_name='bookings_bk_created_7eb52d_idx',
        ),
        migrations.RenameIndex(
            model_name='calllog',
            new_name='bookings_ca_booking_56f706_idx',
            old_name='bookings_ca_booking_idx',
        ),
        migrations.RenameIndex(
            model_name='calllog',
            new_name='bookings_ca_call_sh_cf0bcd_idx',
            old_name='bookings_ca_call_sho_idx',
        ),
        migrations.RenameIndex(
            model_name='calllog',
            new_name='bookings_ca_booking_02d402_idx',
            old_name='bookings_ca_booking_call_idx',
        ),
    ]
