# Generated by Django 4.2.14 on 2026-07-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_bookings_provider_ping_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pending_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pending_timeout_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pending_expires_at'], name='bookings_bo_pending_7833ab_idx'),
        ),
    ]
