# Generated by Django 4.2.14 on 2026-07-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_pending_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reschedule_proposed_for_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reschedule_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reschedule_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reschedule_requested_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='reschedule_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reschedule_status',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_for_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['reschedule_status'], name='bookings_bo_resched_53a429_idx'),
        ),
    ]
