# Generated by Django 4.2.14 on 2026-07-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_reschedule_proposed_for_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_fee_paid_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_fee_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_window_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['accepted_at'], name='bookings_bo_accepte_49e89b_idx'),
        ),
    ]
