# Generated by Django 4.2.14 on 2026-07-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_accepted_at_booking_cancellation_fee_paid_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='call_medium',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=20),
        ),
        migrations.AddField(
            model_name='calllog',
            name='consent_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
