# Generated by Django 4.2.14 on 2026-07-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_ven_onboard_f5e493_idx',
            old_name='vendors_oi_status_47c6e1_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_ven_categor_93852f_idx',
            old_name='vendors_ca_category_0d2dd5_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_ven_created_c4e3ec_idx',
            old_name='vendors_cr_created_4f4e52_idx',
        ),
        migrations.AddField(
            model_name='vendor',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['document_status'], name='vendors_ven_documen_f909ef_idx'),
        ),
    ]
