# Generated by Django 4.2.14 on 2026-07-16 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_rename_vendors_oi_status_47c6e1_idx_vendors_ven_onboard_f5e493_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('listing_type', models.CharField(choices=[('service', 'Service'), ('product', 'Product')], default='service', max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_label', models.CharField(blank=True, max_length=50)),
                ('quantity_available', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Listing',
                'verbose_name_plural': 'Vendor Listings',
                'indexes': [models.Index(fields=['vendor'], name='vendors_ven_vendor__9bd89d_idx'), models.Index(fields=['category'], name='vendors_ven_categor_de35aa_idx'), models.Index(fields=['is_active'], name='vendors_ven_is_acti_a06113_idx'), models.Index(fields=['created_at'], name='vendors_ven_created_5858ad_idx')],
            },
        ),
    ]
