# Generated by Django 4.2.14 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendororder'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='feedback_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='feedback_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]