# Generated by Django 4.2.14 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendororder_feedback_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
    ]