# Generated by Django 4.2.14 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendororder_cancellation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='refund_requested_by',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='refund_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='refund_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='not_required', max_length=20),
        ),
    ]