# Generated by Django 4.2.14 on 2026-07-16 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_accepted_at_booking_cancellation_fee_paid_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('support', 'Support'), ('moderation', 'Moderation'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('harassment', 'Harassment'), ('misconduct', 'Misconduct'), ('fraud', 'Fraud'), ('unsafe_conduct', 'Unsafe Conduct')], max_length=30)),
                ('target_type', models.CharField(choices=[('booking', 'Booking'), ('user', 'User'), ('provider', 'Provider'), ('vendor', 'Vendor')], default='booking', max_length=20)),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('evidence_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('moderator_notes', models.TextField(blank=True)),
                ('moderation_action', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports', to='bookings.booking')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_safety_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reports', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_safety_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'report_type'], name='communicati_status_df7aa1_idx'), models.Index(fields=['target_type'], name='communicati_target__97253a_idx'), models.Index(fields=['reporter', 'status'], name='communicati_reporte_96b502_idx')],
            },
        ),
    ]
