# Generated by Django 4.2.14 on 2026-07-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_notification_category_safetyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyreport',
            name='linked_entity_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='linked_entity_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='target_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='safetyreport',
            index=models.Index(fields=['linked_entity_available'], name='communicati_linked__98b643_idx'),
        ),
    ]
