# Generated by Django 4.2.14 on 2026-07-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_status_7ad4af_idx',
            old_name='payments_status_1c0c7a_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_externa_e30da4_idx',
            old_name='payments_externa_6a7d4d_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_payout__4fd320_idx',
            old_name='payments_payout_4e3d6a_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_created_b8a300_idx',
            old_name='payments_created_0fbf8d_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='dispute_window_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payout_release_at'], name='payments_pa_payout__e36ece_idx'),
        ),
    ]
